#!/bin/bash
# OpenFolio Self-Hosted Setup Script
#
# This script generates required secrets and prepares the environment
# for running OpenFolio via Docker Compose.
#
# Usage: ./scripts/setup.sh

set -e

ENV_FILE=".env"

echo "==================================="
echo "  OpenFolio Self-Hosted Setup"
echo "==================================="
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  echo "Warning: $ENV_FILE already exists."
  read -p "Overwrite? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborting. Edit $ENV_FILE manually if needed."
    exit 0
  fi
fi

# Copy template
if [ -f ".env.example" ]; then
  cp .env.example "$ENV_FILE"
  echo "Copied .env.example to $ENV_FILE"
else
  touch "$ENV_FILE"
  echo "Created empty $ENV_FILE"
fi

# Generate secrets
echo ""
echo "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)

# Write/update secrets in .env
{
  echo ""
  echo "# Generated by setup.sh"
  echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
  echo "JWT_SECRET=$JWT_SECRET"
  echo "INTEGRATION_ENCRYPTION_KEY=$ENCRYPTION_KEY"
  echo "OPENFOLIO_MODE=self-hosted"
  echo "NEXT_PUBLIC_OPENFOLIO_MODE=self-hosted"
} >> "$ENV_FILE"

echo "  POSTGRES_PASSWORD generated"
echo "  JWT_SECRET generated"
echo "  INTEGRATION_ENCRYPTION_KEY generated"
echo "  Self-hosted mode defaults enabled (auth + billing inferred automatically)"

echo ""
echo "==================================="
echo "  Next Steps"
echo "==================================="
echo ""
echo "1. Edit $ENV_FILE and add your API keys:"
echo "   - OPENAI_API_KEY (required for AI features)"
echo "   - GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET (optional, for Gmail sync)"
echo ""
echo "2. Start the services:"
echo "   docker compose up -d"
echo ""
echo "3. Visit http://localhost:3000 to create your account"
echo ""
